language: csharp
sudo: required
# dotnet: 1.0.0-preview2-1-003177

#matrix:
#  include:
#    - os: linux # Ubuntu 14.04
#      dist: trusty
#      mono: latest
#    - os: osx # OSX 10.11
#      osx_image: xcode7.2
#      mono: latest

branches:
  only:
    - master

before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh