language: csharp
sudo: required
dotnet: 1.0.0-preview2-003121

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      mono: latest

branches:
  only:
    - master

before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh